prefix mspd: <http://purl.obolibrary.org/obo/MSPD_>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix owl: <http://www.w3.org/2002/07/owl#>

construct {
    ?instance_iri a ?parent_iri
} where {
  ?class_iri a owl:Class .
  ?class_iri rdfs:subClassOf+ ?parent_iri .
  ?instance_iri a ?class_iri; mspd:patient_id ?pid .
}
