prefix mspd: <http://purl.obolibrary.org/obo/MSPD_>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix owl: <http://www.w3.org/2002/07/owl#>

select ?classLabel ?class_iri(count(distinct ?instance_iri) as ?instance_count)
where {
  ?instance_iri a ?class_iri; mspd:patient_id ?pid .
  ?class_iri rdfs:label ?classLabel . #this says you want the labels that are connected via the predicate (rdfs:label) to a class iri. 
}

group by ?class_iri ?classLabel
order by ?class_iri
